### PR TITLE
fixes #185 No longer write to stdin

### LINKED ISSUE #185: Calling uno within a script fails
There is something about calling uno in a script like the following ...

```bash
cat testClasses.txt | while read test_class; do
  uno setup accumulo
done

```  

... that causes setup to fail with errors like the following :

```
/home/ubuntu/uno/bin/impl/setup-hadoop.sh: line 27: echo: write error: Bad file descriptor
/home/ubuntu/uno/bin/impl/setup-zookeeper.sh: line 26: echo: write error: Bad file descriptor
/home/ubuntu/uno/bin/impl/setup-accumulo.sh: line 33: echo: write error: Bad file descripto
```

I had to remove the file redirection for the setup scripts to see these errors.

### PR DESCRIPTION
**Pull request by keith-turner**

### CODE REVIEW

File: bin/impl/util.sh [hunk 1]
```diff
@@ -59,3 +59,23 @@ function run_setup_script() {
   shift
   "$UNO_HOME/bin/impl/setup-$SCRIP.sh" "$@" 1>"$L_DIR/$SCRIP.stdout" 2>"$L_DIR/$SCRIP.stderr"
 }
+
+function saveConsole {
```
Comment (mikewalch) [inline bin/impl/util.sh]: Could be `saveConsoleFd`

File: bin/impl/util.sh [hunk 2]
```diff
@@ -59,3 +59,23 @@ function run_setup_script() {
...
+  UNO_CONSOLE=''
+  for fd in {0..200}; do
+    rco="$(true 2>/dev/null >&${fd}; echo $?)"
+    rci="$(true 2>/dev/null <&${fd}; echo $?)"
```
Comment (ctubbsii) [inline bin/impl/util.sh]: Local variables should be defined with a local keyword: `local x; x="value"`

File: bin/impl/util.sh [hunk 3]
```diff
@@ -59,3 +59,23 @@ function run_setup_script() {
...
+
+  exec {UNO_CONSOLE}>&1
+  export UNO_CONSOLE
+}
+
+function printToConsole {
+  if [ -z "$UNO_CONSOLE" ]; then
+    echo $1
+  else
+    echo >&${UNO_CONSOLE} $1
```
Comment (ctubbsii) [inline bin/impl/util.sh]: This redirect should not precede the arg. Should be before command or after all args.

Also, instead of `$1` use quoted array: `"$@"` else you only print the first arg.

**Comment by ctubbsii** [comment]
I recommend running shellcheck.

File: bin/impl/util.sh (hunk 3 above)
Comment (keith-turner) [reply bin/impl/util.sh]: In the existing code the redirect preceded the arg for the echos.  I am not sure why it was like that, but I copied it.  Anyway, I fixed it.

File: conf/uno.conf [hunk 4]
```diff
@@ -45,7 +45,7 @@ export FLUO_YARN_TARBALL=fluo-yarn-$FLUO_YARN_VERSION-bin.tar.gz
 # If set, 'uno fetch' will build (instead of downloading) an Accumulo tarball
 # from that directory and copy it to the downloads directory.
 
-#export ACCUMULO_REPO=
+export ACCUMULO_REPO=/home/rkturn2/git/accumulo
```
Comment (ctubbsii) [inline conf/uno.conf]: I assume checking this config in was unintentional?

File: bin/impl/util.sh (hunk 3 above)
Comment (ctubbsii) [reply bin/impl/util.sh]: You're right. It doesn't matter. I was wrong. I don't know what I was thinking. Either way works for me. :smiley_cat:

File: conf/uno.conf (hunk 4 above)
Comment (keith-turner) [reply conf/uno.conf]: Yes it was unintentional and I fixed it, did it again, and then fixed it again.  I miss the old way that Uno worked with the example files.  I am always fighting with git with this file... stashing, unstashing it, having to pick files when  I commit instead of doing all...

File: bin/impl/setup-metrics.sh [hunk 5]
```diff
@@ -94,14 +94,14 @@ $SED "/fluo.metrics.reporter.graphite/d" "$FLUO_PROPS"
   echo "fluo.metrics.reporter.graphite.frequency=30"
 } >> "$FLUO_PROPS"
 
-echo >&0 "Configuring InfluxDB..."
+print_to_console "Configuring InfluxDB..."
```
Comment (ctubbsii) [inline bin/impl/setup-metrics.sh]: These are fine, but one advantage of using the entire arg array rather than `$1` is that these quotes are no longer needed. It's not necessary to remove them, but it's nice to have the option to avoid quotes, in case we run into situations where we have to escape quotes in crazy ways.

File: conf/uno.conf (hunk 4 above)
Comment (ctubbsii) [reply conf/uno.conf]: There are ways you can avoid running into that. Some of the things I do include:

1. Using `git status` before committing, with color output, so changes stand out.
1. Using `git diff HEAD` to verify changes before committing.
1. I also keep master branch pristine, and have a local branch with my local edits; when changes are made to master, I merge to my branch. When I wish to make changes, I do `git checkout -b feature-branch-name origin/master`.

Other suggestions to actually ignore changes to the file can be found at: https://stackoverflow.com/questions/1753070/how-do-i-configure-git-to-ignore-some-files-locally

Comment (keith-turner) [reply conf/uno.conf]: Re 1,2,4,and,5  I usually keep a close eye on what I am pushing for the initial PR and when I push to upstream.  For the commits during the PR, I tend to go with whats fastest.

Re 3.  I can give that a try.  Seems like may be more work than the example file, but I will see.
